[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
solc = "0.8.16"
optimizer = true
optimizer_runs = 10000
gas_reports = ['*']

[profile.default.optimizer_details]
constantOptimizer = true
yul = true
# this sets the `yulDetails` of the `optimizer_details` for the `default` profile
[profile.default.optimizer_details.yulDetails]
stackAllocation = true
optimizerSteps = 'dhfoDgvulfnTUtnIf'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
